#!/bin/bash
#
# $Id: post-uninstall 421 2007-04-05 15:46:55Z dhill $
#
# Post-uninstall steps for erydb install

prefix=/usr/local
installdir=$prefix/erydb
rpmmode=install
SUDO=" "
user=root
if [ $USER != "root" ]; then
        user=$USER
        SUDO="sudo "
fi

quiet=0

for arg in "$@"; do
	if [ `expr -- "$arg" : '--prefix='` -eq 9 ]; then
		prefix="`echo $arg | awk -F= '{print $2}'`"
		installdir=$prefix/erydb
	elif [ `expr -- "$arg" : '--rpmmode='` -eq 10 ]; then
		rpmmode="`echo $arg | awk -F= '{print $2}'`"
	elif [ `expr -- "$arg" : '--installdir='` -eq 13 ]; then
		installdir="`echo $arg | awk -F= '{print $2}'`"
		prefix=`dirname $installdir`
	elif [ `expr -- "$arg" : '--user='` -eq 7 ]; then
		user="`echo $arg | awk -F= '{print $2}'`"
	elif [ `expr -- "$arg" : '--quiet'` -eq 7 ]; then
		quiet=1
	else
		echo "post-uninstall: ignoring unknown argument: $arg" 1>&2
	fi
done

if [ $user = "root" ]; then
	. /root/.bashrc
else
	. $HOME/.bashrc
fi

#stop services
$installdir/bin/erydb stop > /dev/null 2>&1
if test -f /etc/init.d/mysql-erydb ; then
	$installdir/myql/mysql-erydb stop > /dev/null 2>&1
fi

if [ $installdir == "/usr/local/erydb" ]; then
	# remove library config file
	rm -f /etc/ld.so.conf.d/erydb.conf
	rm -f /etc/ld.so.cache
	ldconfig
fi

# uninstall OS scripts updated by postConfigure
if test -f /root/.bashrc.erydbSave ; then
	$sudo mv -f /root/.bashrc.erydbSave /root/.bashrc > /dev/null 2>&1
fi
if test -f /etc/exports.erydbSave ; then
	$SUDO mv -f /etc/exports.erydbSave /etc/exports > /dev/null 2>&1
else
	$SUDO rm -f /etc/exports > /dev/null 2>&1
fi

if test -f /etc/rc.d/rc.local.erydbSave ; then	
	$SUDO mv -f /etc/rc.d/rc.local.erydbSave /etc/rc.d/rc.local > /dev/null 2>&1
fi

if test -f /etc/rc.local.erydbSave ; then
	$SUDO mv -f /etc/rc.local.erydbSave /etc/rc.local > /dev/null 2>&1
fi

export ERYDB_INSTALL_DIR=$installdir

cloud=`$ERYDB_INSTALL_DIR/bin/getConfig Installation Cloud`
if [ $cloud = "amazon-ec2" ] || [ $cloud = "amazon-vpc" ]; then
	if test -f /etc/fstab ; then
		$SUDO sed -i '/Erydb\/data/d' /etc/fstab > /dev/null 2>&1
	fi
fi
 
#remove log file directories
#rm -rf /var/log/erydb > /dev/null 2>&1
#rm -f $installdir/mysql/db/*.err > /dev/null 2>&1
$SUDO rm -f /var/log/erydb/activeAlarms > /dev/null 2>&1
$SUDO rm -f /var/log/erydb/*.log1 > /dev/null 2>&1
rm -rf $installdir/mysql/db/erydb_log_archive > /dev/null 2>&1
$SUDO rm -f /etc/default/erydb

# remove Erydb Log Rotate File abd Transaction Log File
$SUDO rm -f /etc/logrotate.d/erydb > /dev/null 2>&1
$SUDO rm -f /etc/cron.d/transactionLog > /dev/null 2>&1

# delete Erydb shared memory segments
$installdir/bin/clearShm  > /dev/null 2>&1

# delete prat files
$SUDO rm -f /etc/cron.d/ps > /dev/null 2>&1
$SUDO rm -f /etc/pscollect > /dev/null 2>&1
$SUDO /etc/init.d/crond reload  > /dev/null 2>&1
$SUDO systemctl reload crond.service > /dev/null 2>&1

# delete tmp files
rm -f $installdir/local/*.erydb
rm -rf $installdir/local/etc/
rm -rf /tmp/bucketreuse
rm -f /tmp/erydb.txt
rm -f /tmp/dbbuilder.*
rm -f /tmp/dbrmfiles
$SUDO rm -f /var/lock/subsys/erydb
rm -f /tmp/pkgcheck
rm -f /tmp/upgrade-status.log.*
rm -f /tmp/mount.log
rm -f $installdir/data/bulk/tmpjob/* >/dev/null 2>&1
rm -rf /tmp/erydb_tmp_files
rm -f $installdir/local/moveDbrootTransactionLog

#delete any old setenv files under home directory
if [ $user = "root" ]; then
	rm -f /root/setenv-hdfs*
else
	rm -f /home/$user/setenv-hdfs*
fi

# delete core files
#rm -f /var/log/erydb/corefiles/* > /dev/null 2>&1

#uninstall erydb system logging
if [ -x $installdir/bin/syslogSetup.sh ]; then
	if [ $user = "root" ]; then
		$installdir/bin/syslogSetup.sh uninstall >/dev/null 2>&1
	else
		$SUDO $installdir/bin/syslogSetup.sh uninstall >/dev/null 2>&1
	fi
fi

#remove the start service command
if [ $user = "root" ]; then
	systemctl=`which systemctl 2>/dev/null`
	if [ -n "$systemctl" ]; then

		systemctl disable erydb >/dev/null 2>&1
		rm -f /usr/lib/systemd/system/erydb.service
		rm -f /lib/systemd/system/erydb.service
	else
		chkconfig=`which chkconfig 2>/dev/null`
		if [ -n "$chkconfig" ]; then

			chkconfig erydb off > /dev/null 2>&1
			chkconfig --del erydb > /dev/null 2>&1
			rm -f /etc/init.d/erydb > /dev/null 2>&1
		else
			updaterc=`which update-rc.d 2>/dev/null`
			if [ -n "$updaterc" ]; then

				update-rc.d -f erydb remove > /dev/null 2>&1
				rm -f /etc/init.d/erydb > /dev/null 2>&1	
			fi
		fi
	fi
fi

if [ $quiet != 1 ]; then
	#make copy of erydb.xml
	/bin/cp -f $installdir/etc/erydb.xml $installdir/etc/erydb.xml.rpmsave > /dev/null 2>&1
	/bin/cp -f $installdir/mysql/my.cnf $installdir/mysql/my.cnf.rpmsave > /dev/null 2>&1
	rm -f $installdir/etc/AlarmConfig.xml.installSave
fi

#umount file systems
if [ $user = "root" ]; then
	rm -f $installdir/data*/OAMdbrootCheck > /dev/null 2>&1
else
	$SUDO rm -f $installdir/data*/OAMdbrootCheck > /dev/null 2>&1
fi

#remove library paths
if [ $installdir == "/usr/local/erydb" ]; then
        # remove library config file
        $SUDO rm -f /etc/ld.so.conf.d/erydb.conf
        $SUDO ldconfig
fi

#cleanup .bashrc	
if [ $user = "root" ]; then
        if test -f /root/.bashrc.erydbSave ; then
                mv -f /root/.bashrc.erydbSave /root/.bashrc > /dev/null 2>&1
        fi
else
        if test -f $HOME/.bashrc.erydbSave ; then
                mv -f /home/$user/.bashrc.erydbSave /home/$user/.bashrc > /dev/null 2>&1
        fi
fi

#tell user to run post configure script
echo " "
echo "Erydb uninstall completed"

exit 0

