#!/bin/bash
#
# $Id: post-mysql-install 3661 2013-06-25 22:04:33Z dhill $
#
# Post-install steps for erydb-mysql install

# check log for error
checkForError() {
	# check for password error
	grep "ERROR 1045" /tmp/mysql_install.log > /tmp/error.check
	if [ `cat /tmp/error.check | wc -c` -ne 0 ]; then
		password=`$installdir/bin/getMySQLpw`
		if [ $? -ne 0 ]; then
			echo "MySQL Password missing or incorrect"
			rm -f /tmp/error.check
			$installdir/mysql/mysql-erydb stop
			sleep 2
			exit 2;
		fi
		rm -f /tmp/error.check
		return 1;
	fi

	rm -f /tmp/error.check

        #---------------------------------------------------------------------------
        # See if engine erydb exist
        #---------------------------------------------------------------------------
        echo "checking for engine erydb..."
        $installdir/mysql/bin/mysql \
                --defaults-file=$installdir/mysql/my.cnf \
                --user=root $pwprompt \
                --execute='show engines;' \
                erydbsys | grep -i erydb

        #
        # Add compressiontype column to SYSCOLUMN if applicable
        #
        if [ $? -ne 0 ]; then
                echo "erydb doesn\'t exist"
                return 1
        fi

        echo "erydb exist"

	return 0;
}

prefix=/usr/local
installdir=$prefix/erydb
rpmmode=install
password=

for arg in "$@"; do
	if [ $(expr -- "$arg" : '--prefix=') -eq 9 ]; then
		prefix="$(echo $arg | awk -F= '{print $2}')"
		installdir=$prefix/erydb
	elif [ $(expr -- "$arg" : '--rpmmode=') -eq 10 ]; then
		rpmmode="$(echo $arg | awk -F= '{print $2}')"
	elif [ $(expr -- "$arg" : '--password=') -eq 11 ]; then
		password="$(echo $arg | awk -F= '{print $2}')"
	elif [ $(expr -- "$arg" : '--installdir=') -eq 13 ]; then
		installdir="$(echo $arg | awk -F= '{print $2}')"
		prefix=$(dirname $installdir)
	else
		echo "ignoring unknown argument: $arg" 1>&2
	fi
done


rm -rf /etc/my.cnf && ln -sf $installdir/mysql/my.cnf /etc/my.cnf 
logError=`cat /etc/my.cnf |grep "log-error"|awk -F= '{print $2}'`
if [ "$logError" != "" ] ; then
	logError=`dirname "logError"`
	mkdir -p $logError
else
   mkdir -p /var/log/mariadb
fi
pidFile=`cat /etc/my.cnf |grep "pid-file"|awk -F= '{print $2}'`
if [ "$pidFile" != "" ] ; then
	pidFile=`dirname "pidFile"`
	mkdir -p $pidFile
else
   mkdir -p /var/run/mariadb
fi
#run to make sure library paths are setup
ldconfig

if [ $installdir != "/usr/local/erydb" ]; then
	export ERYDB_INSTALL_DIR=$installdir
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ERYDB_INSTALL_DIR/lib:$ERYDB_INSTALL_DIR/mysql/lib/plugin
fi

if [ -f $installdir/lib/libcalmysql.so.1.0.0 ]; then
	libcalmysql=$installdir/lib/libcalmysql.so.1.0.0
	libudfsdk=$installdir/lib/libudfsdk.so.1.0.0
	libudfmysql=$installdir/lib/libudf_mysql.so.1.0.0
elif [ -f $installdir/lib/libcalmysql.so.1 ]; then
	libcalmysql=$installdir/lib/libcalmysql.so.1
	libudfsdk=$installdir/lib/libudfsdk.so.1
	libudfmysql=$installdir/lib/libudf_mysql.so.1
else
	libcalmysql=
fi

if [ -d $installdir/mysql/lib/plugin -a -n "$libcalmysql" ]; then
	cd $installdir/mysql/lib/plugin
	ln -sf $libcalmysql libcalmysql.so
  ln -sf $libcalmysql libcalmysqlent.so
	ln -sf $libudfsdk libudfsdk.so
	ln -sf $libudfmysql libudf_mysql.so
fi

if [ $installdir != "/usr/local/erydb" ]; then
	sed -i -e s@/usr/local/erydb@$installdir@g $installdir/mysql/my.cnf
fi

if [ -x $installdir/mysql/mysql-erydb ]; then

	# Restart in the same way that mysqld will be started normally.
	$installdir/mysql/mysql-erydb stop >/dev/null 2>&1
	sleep 2
	$installdir/mysql/mysql-erydb start

	sleep 5

	# Install various erydb stuff...
	$installdir/mysql/install_erydb_mysql.sh --password=$password --installdir=$installdir
	checkForError
	if [ $? -ne 0 ]; then
	# retry
		$installdir/mysql/install_erydb_mysql.sh --password=$password --installdir=$installdir
		checkForError
		if [ $? -ne 0 ]; then
			echo "ERROR: missing or invalid password, or EryDB plugin install missing"
			$installdir/mysql/mysql-erydb stop
			sleep 2
			exit 1;
		fi
	fi

	$installdir/mysql/mysql-erydb stop
fi

exit 0

